### ISSUE TITLE
Installation using composer doesn't works

### ISSUE THREAD

**Issue by zealfire** [php-poppler/php-poppler#2]
@temp  hi,when I try to make installation using this command: `composer update php-poppler/php-poppler` , the installation doesn't happens and I encountered following error:
`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package php-poppler/php-poppler could not be found in any ve
rsion, there may be a typo in the package name.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your min
  imum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion f
  or more details.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further commo
n problems.` Can u please look into this. Thanks.

**Comment by temp** [comment]
Please try "composer require php-poppler/php-poppler" for installation.
After it is installed, you can update it with "composer update php-poppler/php-poppler".
But at first it has to be installed...
Please refer to https://getcomposer.org/doc/03-cli.md#require for further details.
